default: &default
  adapter: <%= ActiveRecord::Base.connection.adapter_name == "SQLite" ? "sqlite" : "mysql_sharded" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

beta:
  <<: *default

staging:
  <<: *default
